name: Android Custom Menu Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Depodan Cek
      uses: actions/checkout@v4

    - name: Android NDK Ortamini Kur
      uses: nndst/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: ndk-build ile Derleme Islemini Baslat
      run: |
        ndk-build -C ./jni

    - name: Derlenen .so Dosyalarini Yukle
      uses: actions/upload-artifact@v4
      with:
        name: Polyfield-OzelMenu-Libs
        path: libs/
        
