name: Build Screen Share Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Depoyu Indir
      uses: actions/checkout@v4

    - name: MSVC Derleyici Ortamini Kur
      uses: ilammy/msvc-dev-cmd@v1

    - name: C++ Kodunu Derle
      run: |
        cl.exe /EHsc main.cpp /Fe:ScreenShareServer.exe gdiplus.lib ws2_32.lib user32.lib gdi32.lib ole32.lib

    - name: Exe Dosyasini Yukle (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: ScreenShareServer
        path: ScreenShareServer.exe
